# Server Configuration
server.port=8761

# Eureka Server Configuration for faster instance eviction
eureka.server.eviction-interval-timer-in-ms=10000
eureka.server.enable-self-preservation=false

# Eureka Client Configuration
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
